"use client";

import { useState, useEffect, useCallback, useMemo, useRef } from "react";
import { slugify, validateSlug } from "@/lib/utils/slug";

interface UseSlugOptions {
  /** The source field to generate slug from (e.g., name) */
  source: string;
  /** Initial slug value */
  initialSlug?: string;
  /** Whether to auto-generate slug from source */
  autoGenerate?: boolean;
  /** Callback to check if slug is unique */
  onSlugChange?: (slug: string) => void;
}

interface UseSlugReturn {
  /** Current slug value */
  slug: string;
  /** Whether slug was manually edited */
  isManuallyEdited: boolean;
  /** Set slug value */
  setSlug: (value: string) => void;
  /** Mark slug as manually edited */
  markAsManuallyEdited: () => void;
  /** Reset to auto-generated slug */
  resetToAutoGenerated: () => void;
  /** Validation state */
  validation: { isValid: boolean; error?: string };
}

/**
 * Hook for managing slug fields with auto-generation and manual override
 *
 * @example
 * const { slug, setSlug, isManuallyEdited, validation } = useSlug({
 *   source: name,
 *   initialSlug: product?.slug,
 *   autoGenerate: true,
 * });
 */
export function useSlug({
  source,
  initialSlug = "",
  autoGenerate = true,
  onSlugChange,
}: UseSlugOptions): UseSlugReturn {
  const [manualSlug, setManualSlug] = useState<string | null>(null);
  const [isManuallyEdited, setIsManuallyEdited] = useState(false);

  // Keep track of previous source to detect changes
  const prevSourceRef = useRef(source);

  // Derive the slug - use manual slug if edited, otherwise auto-generate
  const slug = useMemo(() => {
    if (isManuallyEdited && manualSlug !== null) {
      return manualSlug;
    }
    if (autoGenerate && source) {
      return slugify(source);
    }
    return initialSlug;
  }, [isManuallyEdited, manualSlug, autoGenerate, source, initialSlug]);

  // Notify parent when slug changes (but not on initial render)
  const isInitialMount = useRef(true);
  useEffect(() => {
    if (isInitialMount.current) {
      isInitialMount.current = false;
      return;
    }

    // Only call onSlugChange when source changes and we're auto-generating
    if (source !== prevSourceRef.current && autoGenerate && !isManuallyEdited) {
      prevSourceRef.current = source;
      onSlugChange?.(slug);
    }
  }, [slug, source, autoGenerate, isManuallyEdited, onSlugChange]);

  // Use useMemo to compute validation without causing re-renders
  const validation = useMemo(() => {
    if (slug) {
      return validateSlug(slug);
    }
    return { isValid: true };
  }, [slug]);

  const setSlug = useCallback(
    (value: string) => {
      setManualSlug(value);
      setIsManuallyEdited(true);
      onSlugChange?.(value);
    },
    [onSlugChange]
  );

  const markAsManuallyEdited = useCallback(() => {
    setIsManuallyEdited(true);
  }, []);

  const resetToAutoGenerated = useCallback(() => {
    setManualSlug(null);
    setIsManuallyEdited(false);
    const newSlug = slugify(source);
    onSlugChange?.(newSlug);
  }, [source, onSlugChange]);

  return {
    slug,
    isManuallyEdited,
    setSlug,
    markAsManuallyEdited,
    resetToAutoGenerated,
    validation,
  };
}
