import type { MetadataRoute } from "next";
import { db } from "@/lib/db";
import { tenants } from "@/lib/db/schema";
import { eq } from "drizzle-orm";

// Force dynamic generation at request time (not build time)
// This ensures database is available and sitemap is always fresh
export const dynamic = "force-dynamic";

/**
 * Main sitemap index for the platform
 * Includes platform pages and all active store homepages
 *
 * Each store also has its own detailed sitemap at /store/[slug]/sitemap.xml
 * with all products and categories
 *
 * @see https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://kakamalem.com";

  // Platform-level pages
  const platformPages: MetadataRoute.Sitemap = [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 1,
    },
    {
      url: `${baseUrl}/privacy`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.3,
    },
    {
      url: `${baseUrl}/terms`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.3,
    },
    {
      url: `${baseUrl}/data-deletion`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.2,
    },
  ];

  try {
    // Get all active stores
    const activeStores = await db
      .select({
        slug: tenants.slug,
        updatedAt: tenants.updatedAt,
      })
      .from(tenants)
      .where(eq(tenants.status, "active"));

    // Store homepage entries
    // Note: Each store's products and categories are in their own sitemap
    // at /store/[slug]/sitemap.xml (generated by app/store/[slug]/sitemap.ts)
    const storePages: MetadataRoute.Sitemap = activeStores.map((store) => ({
      url: `${baseUrl}/store/${store.slug}`,
      lastModified: store.updatedAt ? new Date(store.updatedAt) : new Date(),
      changeFrequency: "daily" as const,
      priority: 0.9,
    }));

    return [...platformPages, ...storePages];
  } catch {
    // Return only platform pages if database is unavailable (e.g., during CI builds)
    return platformPages;
  }
}
