"use client";

import { RefreshCw, Check, AlertCircle } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

interface SlugInputProps {
  /** Current slug value */
  value: string;
  /** Callback when slug changes */
  onChange: (value: string) => void;
  /** Whether slug was manually edited */
  isManuallyEdited: boolean;
  /** Reset to auto-generated slug */
  onReset: () => void;
  /** Label for the input */
  label?: string;
  /** Placeholder text */
  placeholder?: string;
  /** URL prefix to show before slug */
  urlPrefix?: string;
  /** Whether the input is disabled */
  disabled?: boolean;
  /** Validation error message */
  error?: string;
  /** Whether the slug is valid */
  isValid?: boolean;
  /** Additional class names */
  className?: string;
}

/**
 * A professional slug input component with auto-generation indicator and reset functionality
 *
 * @example
 * <SlugInput
 *   value={slug}
 *   onChange={setSlug}
 *   isManuallyEdited={isManuallyEdited}
 *   onReset={resetToAutoGenerated}
 *   urlPrefix="https://kakamalem.com/store/mystore/product/"
 * />
 */
export function SlugInput({
  value,
  onChange,
  isManuallyEdited,
  onReset,
  label = "URL Slug",
  placeholder = "auto-generated-slug",
  urlPrefix,
  disabled = false,
  error,
  isValid = true,
  className,
}: SlugInputProps) {
  return (
    <div className={cn("space-y-2", className)}>
      {/* Label with status badge */}
      <div className="flex items-center justify-between">
        <Label htmlFor="slug-input" className="text-sm font-medium">
          {label}
        </Label>
        {isManuallyEdited ? (
          <Badge variant="secondary" className="text-xs">
            Custom
          </Badge>
        ) : (
          <Badge variant="outline" className="text-xs">
            Auto-generated
          </Badge>
        )}
      </div>

      {/* URL Preview */}
      {urlPrefix && (
        <div className="rounded-md border bg-muted/30 px-3 py-2 text-xs text-muted-foreground">
          <span className="break-all">
            {urlPrefix}
            <span className="font-medium text-foreground">
              {value || placeholder}
            </span>
          </span>
        </div>
      )}

      {/* Input with reset button */}
      <div className="flex gap-2">
        <div className="relative flex-1">
          <Input
            id="slug-input"
            type="text"
            value={value}
            onChange={(e) => onChange(e.target.value)}
            placeholder={placeholder}
            disabled={disabled}
            className={cn(
              "pr-8",
              error && "border-destructive focus-visible:ring-destructive",
              isValid &&
                value &&
                "border-green-500 focus-visible:ring-green-500"
            )}
          />
          {/* Status icon */}
          <div className="absolute right-2 top-1/2 -translate-y-1/2">
            {error ? (
              <AlertCircle className="size-4 text-destructive" />
            ) : isValid && value ? (
              <Check className="size-4 text-green-500" />
            ) : null}
          </div>
        </div>

        {/* Reset button - only show if manually edited */}
        {isManuallyEdited && (
          <Button
            type="button"
            variant="outline"
            size="icon"
            onClick={onReset}
            disabled={disabled}
            title="Reset to auto-generated slug"
          >
            <RefreshCw className="size-4" />
          </Button>
        )}
      </div>

      {/* Error message or help text */}
      {error ? (
        <p className="text-xs text-destructive">{error}</p>
      ) : (
        <p className="text-xs text-muted-foreground">
          {isManuallyEdited
            ? "You've customized this slug. Click the reset button to auto-generate from the name."
            : "Automatically generated from the name field. Edit to customize."}
        </p>
      )}
    </div>
  );
}
