/**
 * Slug generation utilities with auto-deduplication
 * Industry-standard slug generation following best practices
 * Supports Unicode characters (Persian, Arabic, etc.)
 */

/**
 * Convert a string to a URL-friendly slug
 * - Normalizes Unicode (NFKC normalization for compatibility)
 * - Converts to lowercase
 * - Preserves Unicode letters and numbers (Persian, Arabic, etc.)
 * - Replaces spaces and underscores with hyphens
 * - Removes special characters (punctuation, symbols)
 * - Removes consecutive hyphens
 * - Trims hyphens from start/end
 */
export function slugify(text: string): string {
  return (
    text
      .toString()
      // Normalize Unicode characters (NFKC for compatibility)
      .normalize("NFKC")
      .toLowerCase()
      .trim()
      // Replace spaces and underscores with hyphens
      .replace(/[\s_]+/g, "-")
      // Keep only Unicode letters, numbers, and hyphens
      // \p{L} matches any letter (including Persian, Arabic, etc.)
      // \p{N} matches any number
      .replace(/[^\p{L}\p{N}-]+/gu, "")
      // Replace multiple hyphens with single hyphen
      .replace(/-{2,}/g, "-")
      // Remove hyphens from start and end
      .replace(/^-+/, "")
      .replace(/-+$/, "")
  );
}

/**
 * Convert a string to an ASCII-only slug (for store URLs)
 * - Strips all non-ASCII characters
 * - Returns empty string if no ASCII characters remain
 * Use this for store slugs where ASCII URLs are preferred
 */
export function slugifyAscii(text: string): string {
  return (
    text
      .toString()
      .normalize("NFKD")
      // Remove diacritics (accents)
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .trim()
      // Replace spaces and underscores with hyphens
      .replace(/[\s_]+/g, "-")
      // Keep only ASCII letters, numbers, and hyphens
      .replace(/[^a-z0-9-]+/g, "")
      // Replace multiple hyphens with single hyphen
      .replace(/-{2,}/g, "-")
      // Remove hyphens from start and end
      .replace(/^-+/, "")
      .replace(/-+$/, "")
  );
}

/**
 * Generate a unique slug by appending a number if the slug already exists
 * @param baseSlug - The base slug to start with
 * @param existingSlugs - Array of existing slugs to check against
 * @param maxLength - Maximum length for the slug (default: 255)
 * @returns A unique slug
 */
export function generateUniqueSlug(
  baseSlug: string,
  existingSlugs: string[],
  maxLength: number = 255
): string {
  // Ensure base slug is properly formatted
  let slug = slugify(baseSlug);

  // Truncate to max length, leaving room for suffix
  if (slug.length > maxLength - 10) {
    slug = slug.substring(0, maxLength - 10);
  }

  // If slug doesn't exist, return it
  if (!existingSlugs.includes(slug)) {
    return slug;
  }

  // Find the next available number suffix
  let counter = 1;
  let uniqueSlug = `${slug}-${counter}`;

  while (existingSlugs.includes(uniqueSlug)) {
    counter++;
    uniqueSlug = `${slug}-${counter}`;

    // Safety check to prevent infinite loops
    if (counter > 9999) {
      // Append timestamp as last resort
      uniqueSlug = `${slug}-${Date.now()}`;
      break;
    }
  }

  return uniqueSlug;
}

/**
 * Smart slug updater that only changes slug if it's auto-generated
 * @param currentName - Current name field value
 * @param currentSlug - Current slug field value
 * @param previousName - Previous name field value (to detect if name changed)
 * @param previousSlug - Previous slug field value (to detect manual edits)
 * @returns Updated slug or null if no update needed
 */
export function shouldUpdateSlug(
  currentName: string,
  currentSlug: string,
  previousName: string
): { shouldUpdate: boolean; newSlug: string } {
  // If slug was manually edited (doesn't match slugified previous name), don't auto-update
  const expectedSlug = slugify(previousName);
  const wasAutoGenerated = currentSlug === expectedSlug || currentSlug === "";

  if (!wasAutoGenerated) {
    return { shouldUpdate: false, newSlug: currentSlug };
  }

  // If name changed and slug was auto-generated, update it
  if (currentName !== previousName) {
    return { shouldUpdate: true, newSlug: slugify(currentName) };
  }

  return { shouldUpdate: false, newSlug: currentSlug };
}

/**
 * Validate slug format (supports Unicode)
 * @param slug - The slug to validate
 * @returns Object with isValid and error message
 */
export function validateSlug(slug: string): {
  isValid: boolean;
  error?: string;
} {
  if (!slug || slug.length === 0) {
    return { isValid: false, error: "Slug cannot be empty" };
  }

  if (slug.length > 255) {
    return { isValid: false, error: "Slug cannot exceed 255 characters" };
  }

  // Check if slug matches the slugified version (no special chars, spaces, etc.)
  const slugified = slugify(slug);
  if (slug !== slugified) {
    return {
      isValid: false,
      error: "Slug can only contain letters, numbers, and hyphens",
    };
  }

  // Check for reserved slugs
  const reservedSlugs = [
    "admin",
    "api",
    "auth",
    "dashboard",
    "store",
    "new",
    "edit",
    "delete",
    "settings",
    "login",
    "logout",
    "signup",
    "register",
  ];

  if (reservedSlugs.includes(slug)) {
    return {
      isValid: false,
      error: "This slug is reserved and cannot be used",
    };
  }

  return { isValid: true };
}

/**
 * Generate a SKU from product name
 * - Normalizes Unicode (NFKC normalization for compatibility)
 * - Converts to UPPERCASE
 * - Preserves Unicode letters and numbers (Persian, Arabic, etc.)
 * - Replaces spaces with hyphens
 * - Removes special characters
 * - Truncates to reasonable length
 */
export function generateSku(text: string): string {
  return (
    text
      .toString()
      // Normalize Unicode characters (NFKC for compatibility)
      .normalize("NFKC")
      .toUpperCase()
      .trim()
      // Replace spaces and underscores with hyphens
      .replace(/[\s_]+/g, "-")
      // Keep only Unicode letters, numbers, and hyphens
      // \p{L} matches any letter (including Persian, Arabic, etc.)
      // \p{N} matches any number
      .replace(/[^\p{L}\p{N}-]+/gu, "")
      // Replace multiple hyphens with single hyphen
      .replace(/-{2,}/g, "-")
      // Remove hyphens from start and end
      .replace(/^-+/, "")
      .replace(/-+$/, "")
      // Truncate to 100 characters (schema limit)
      .substring(0, 100)
  );
}

/**
 * Validate ASCII-only slug format (for store URLs)
 * @param slug - The slug to validate
 * @returns Object with isValid and error message
 */
export function validateAsciiSlug(slug: string): {
  isValid: boolean;
  error?: string;
} {
  if (!slug || slug.length === 0) {
    return { isValid: false, error: "Slug cannot be empty" };
  }

  if (slug.length > 63) {
    return { isValid: false, error: "Slug cannot exceed 63 characters" };
  }

  // ASCII-only regex: lowercase letters, numbers, hyphens
  const asciiSlugRegex = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
  if (!asciiSlugRegex.test(slug)) {
    return {
      isValid: false,
      error:
        "Slug can only contain lowercase letters (a-z), numbers, and hyphens",
    };
  }

  // Check for reserved slugs
  const reservedSlugs = [
    "admin",
    "api",
    "auth",
    "dashboard",
    "store",
    "new",
    "edit",
    "delete",
    "settings",
    "login",
    "logout",
    "signup",
    "register",
  ];

  if (reservedSlugs.includes(slug)) {
    return {
      isValid: false,
      error: "This slug is reserved and cannot be used",
    };
  }

  return { isValid: true };
}
