#!/bin/bash

# =============================================================================
# Kaka Malem - Zero-Downtime Blue-Green Deployment
# =============================================================================
# Deploys with zero downtime by running two containers (blue/green) and
# switching Nginx between them.
#
# Usage:
#   ./docker-deploy.sh              # Pull and deploy latest
#   ./docker-deploy.sh --build      # Build locally and deploy
#   ./docker-deploy.sh --rollback   # Rollback to previous version
#   ./docker-deploy.sh --status     # Show current deployment status
# =============================================================================

set -e

# Configuration
APP_DIR="/var/www/kakamalem"
UPSTREAM_CONF="/etc/nginx/conf.d/kakamalem-upstream.conf"
STATE_FILE="$APP_DIR/.deploy-state"
LOG_FILE="$APP_DIR/.logs/docker-deploy_$(date +%Y%m%d_%H%M%S).log"

BLUE_PORT=3000
GREEN_PORT=3001
BLUE_SERVICE="app-blue"
GREEN_SERVICE="app-green"
BLUE_CONTAINER="kakamalem-blue"
GREEN_CONTAINER="kakamalem-green"

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${GREEN}[$(date '+%H:%M:%S')]${NC} $1" | tee -a "$LOG_FILE"; }
warn() { echo -e "${YELLOW}[$(date '+%H:%M:%S')] WARNING:${NC} $1" | tee -a "$LOG_FILE"; }
error() { echo -e "${RED}[$(date '+%H:%M:%S')] ERROR:${NC} $1" | tee -a "$LOG_FILE"; exit 1; }

# Ensure directories exist
mkdir -p "$(dirname $LOG_FILE)"

# Change to app directory
cd "$APP_DIR" || error "Failed to change to $APP_DIR"

# -----------------------------------------------------------------------------
# Helper Functions
# -----------------------------------------------------------------------------

get_current_active() {
    if [ -f "$STATE_FILE" ]; then
        cat "$STATE_FILE"
    else
        # Check which container is running, default to blue
        if docker ps --format '{{.Names}}' | grep -q "$BLUE_CONTAINER"; then
            echo "blue"
        elif docker ps --format '{{.Names}}' | grep -q "$GREEN_CONTAINER"; then
            echo "green"
        else
            echo "none"
        fi
    fi
}

set_active() {
    echo "$1" > "$STATE_FILE"
}

get_port_for_color() {
    if [ "$1" = "blue" ]; then
        echo "$BLUE_PORT"
    else
        echo "$GREEN_PORT"
    fi
}

get_service_for_color() {
    if [ "$1" = "blue" ]; then
        echo "$BLUE_SERVICE"
    else
        echo "$GREEN_SERVICE"
    fi
}

get_container_for_color() {
    if [ "$1" = "blue" ]; then
        echo "$BLUE_CONTAINER"
    else
        echo "$GREEN_CONTAINER"
    fi
}

wait_for_healthy() {
    local port=$1
    local max_retries=60
    local retry_count=0
    local health_url="http://localhost:$port/api/health"

    log "Waiting for app on port $port to be healthy..."

    while [ $retry_count -lt $max_retries ]; do
        if curl -sf "$health_url" > /dev/null 2>&1; then
            log "App on port $port is healthy!"
            return 0
        fi

        retry_count=$((retry_count + 1))
        echo -n "."
        sleep 2
    done

    echo ""
    warn "Health check failed after $max_retries attempts on port $port"
    return 1
}

update_nginx_upstream() {
    local primary_port=$1
    local backup_port=$2

    log "Updating Nginx upstream: primary=$primary_port, backup=$backup_port"

    cat > "$UPSTREAM_CONF" << EOF
# Auto-generated by docker-deploy.sh - DO NOT EDIT MANUALLY
# Updated: $(date)
upstream kakamalem_app {
    server 127.0.0.1:$primary_port;
    server 127.0.0.1:$backup_port backup;
}
EOF

    # Test and reload nginx
    if nginx -t 2>&1 | tee -a "$LOG_FILE"; then
        systemctl reload nginx
        log "Nginx reloaded successfully"
    else
        error "Nginx config test failed!"
    fi
}

show_status() {
    local current=$(get_current_active)

    echo ""
    echo "==========================================================================="
    echo "Deployment Status"
    echo "==========================================================================="
    echo ""

    echo "Active slot: $current"
    echo ""

    echo "Containers:"
    docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep -E "(NAMES|kakamalem)" || echo "  No containers running"
    echo ""

    echo "Nginx upstream config:"
    if [ -f "$UPSTREAM_CONF" ]; then
        cat "$UPSTREAM_CONF"
    else
        echo "  Not configured yet"
    fi
    echo ""

    echo "Health checks:"
    for port in $BLUE_PORT $GREEN_PORT; do
        if curl -sf "http://localhost:$port/api/health" > /dev/null 2>&1; then
            echo "  Port $port: ${GREEN}healthy${NC}"
        else
            echo "  Port $port: ${RED}not responding${NC}"
        fi
    done
    echo ""
}

# -----------------------------------------------------------------------------
# Pre-flight checks
# -----------------------------------------------------------------------------

preflight_checks() {
    log "Running pre-flight checks..."

    if ! docker info &> /dev/null; then
        error "Docker is not running"
    fi

    if [ ! -f "docker-compose.yml" ]; then
        error "docker-compose.yml not found in $APP_DIR"
    fi

    if [ ! -f ".env" ]; then
        error ".env file not found in $APP_DIR"
    fi

    log "Pre-flight checks passed"
}

# -----------------------------------------------------------------------------
# Main Deployment Logic
# -----------------------------------------------------------------------------

deploy() {
    local build_locally=$1

    preflight_checks

    # Run database migrations before deploying
    log "Running database migrations..."
    if pnpm db:migrate 2>&1 | tee -a "$LOG_FILE"; then
        log "Migrations completed successfully"
    else
        error "Migration failed! Aborting deployment."
    fi

    # Determine current and target slots
    local current=$(get_current_active)
    local target

    if [ "$current" = "blue" ] || [ "$current" = "none" ]; then
        target="green"
    else
        target="blue"
    fi

    local target_port=$(get_port_for_color $target)
    local target_service=$(get_service_for_color $target)
    local target_container=$(get_container_for_color $target)

    local current_port=$(get_port_for_color $current)

    log "Current active: $current (port $current_port)"
    log "Deploying to: $target (port $target_port)"

    # Pull or build the new image
    if [ "$build_locally" = "true" ]; then
        log "Building Docker image locally..."
        docker compose build --no-cache $target_service 2>&1 | tee -a "$LOG_FILE"
    else
        log "Pulling latest image..."
        docker compose pull $target_service 2>&1 | tee -a "$LOG_FILE"
    fi

    # Stop target container if running (from previous deployment)
    if docker ps -a --format '{{.Names}}' | grep -q "$target_container"; then
        log "Stopping old $target container..."
        docker compose stop $target_service 2>&1 | tee -a "$LOG_FILE"
        docker compose rm -f $target_service 2>&1 | tee -a "$LOG_FILE"
    fi

    # Start the new container
    log "Starting new $target container..."
    docker compose up -d $target_service 2>&1 | tee -a "$LOG_FILE"

    # Wait for it to be healthy
    if ! wait_for_healthy $target_port; then
        error "New container failed health check. Aborting deployment."
    fi

    # Switch traffic to new container
    if [ "$current" = "none" ]; then
        # First deployment - set target as primary, other port as backup (won't be used)
        if [ "$target" = "blue" ]; then
            update_nginx_upstream $BLUE_PORT $GREEN_PORT
        else
            update_nginx_upstream $GREEN_PORT $BLUE_PORT
        fi
    else
        # Normal deployment - target becomes primary, current becomes backup
        update_nginx_upstream $target_port $current_port
    fi

    # Update state
    set_active $target

    # Wait a moment for traffic to drain, then stop old container
    if [ "$current" != "none" ]; then
        log "Waiting 10s for connections to drain..."
        sleep 10

        local current_service=$(get_service_for_color $current)
        log "Stopping old $current container..."
        docker compose stop $current_service 2>&1 | tee -a "$LOG_FILE"
    fi

    # Cleanup old images
    log "Cleaning up old images..."
    docker image prune -f 2>&1 | tee -a "$LOG_FILE"

    log "============================================================================="
    log "Deployment completed successfully!"
    log "Active: $target (port $target_port)"
    log "============================================================================="

    show_status
}

rollback() {
    preflight_checks

    local current=$(get_current_active)
    local target

    if [ "$current" = "blue" ]; then
        target="green"
    elif [ "$current" = "green" ]; then
        target="blue"
    else
        error "No previous deployment to rollback to"
    fi

    local target_port=$(get_port_for_color $target)
    local target_service=$(get_service_for_color $target)
    local current_port=$(get_port_for_color $current)
    local current_service=$(get_service_for_color $current)

    log "Rolling back from $current to $target..."

    # Start the previous container (should still have the old image)
    log "Starting $target container..."
    docker compose up -d $target_service 2>&1 | tee -a "$LOG_FILE"

    if ! wait_for_healthy $target_port; then
        error "Rollback failed - previous container won't start"
    fi

    # Switch traffic
    update_nginx_upstream $target_port $current_port

    # Update state
    set_active $target

    # Stop the bad container
    sleep 5
    docker compose stop $current_service 2>&1 | tee -a "$LOG_FILE"

    log "============================================================================="
    log "Rollback completed!"
    log "Active: $target (port $target_port)"
    log "============================================================================="

    show_status
}

# -----------------------------------------------------------------------------
# Initialize upstream config if missing
# -----------------------------------------------------------------------------

init_upstream() {
    if [ ! -f "$UPSTREAM_CONF" ]; then
        log "Creating initial Nginx upstream config..."
        update_nginx_upstream $BLUE_PORT $GREEN_PORT
    fi
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

case "$1" in
    --build)
        init_upstream
        deploy "true"
        ;;
    --rollback)
        rollback
        ;;
    --status)
        show_status
        ;;
    *)
        init_upstream
        deploy "false"
        ;;
esac
