/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    'product-variants': ProductVariant;
    orders: Order;
    reviews: Review;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-variants': ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    terms: Term;
    'privacy-policy': PrivacyPolicy;
    help: Help;
    shipping: Shipping;
    contact: Contact;
    faqs: Faq;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    terms: TermsSelect<false> | TermsSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    help: HelpSelect<false> | HelpSelect<true>;
    shipping: ShippingSelect<false> | ShippingSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  password?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Available authentication methods (system-managed)
   */
  authMethods?: ('password' | 'google')[] | null;
  /**
   * Google OAuth subject ID (system-managed)
   */
  googleSub?: string | null;
  /**
   * Profile picture URL (system-managed)
   */
  picture?: string | null;
  /**
   * User-uploaded profile picture
   */
  profilePicture?: (string | null) | Media;
  /**
   * Original Fan - Early supporter badge
   */
  ogfan?: boolean | null;
  phone?: string | null;
  /**
   * User roles determine access levels. Only superadmins and developers can modify roles.
   */
  roles?: ('customer' | 'seller' | 'admin' | 'superadmin' | 'developer')[] | null;
  addresses?:
    | {
        label: string;
        firstName: string;
        lastName: string;
        /**
         * Province or region
         */
        state?: string | null;
        country: string;
        phone?: string | null;
        isDefault?: boolean | null;
        /**
         * Well-known nearby landmark (mosque, shop, building, etc.)
         */
        nearbyLandmark?: string | null;
        /**
         * Step-by-step directions to help delivery find your location
         */
        detailedDirections?: string | null;
        /**
         * GPS location - Pin your exact location on the map
         */
        coordinates?: {
          /**
           * Latitude coordinate
           */
          latitude?: number | null;
          /**
           * Longitude coordinate
           */
          longitude?: number | null;
          /**
           * Location accuracy in meters
           */
          accuracy?: number | null;
          /**
           * How the location was obtained
           */
          source?: ('gps' | 'ip' | 'manual' | 'map') | null;
          /**
           * IP address when location was captured
           */
          ip?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  preferences?: {
    currency?: ('AFN' | 'USD') | null;
    newsletter?: boolean | null;
  };
  /**
   * Shopping cart data (managed via API, JSON format)
   */
  cart?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Products added to wishlist
   */
  wishlist?: (string | Product)[] | null;
  /**
   * Recently viewed products (managed via API, max 20 items)
   */
  recentlyViewed?:
    | {
        product: string | Product;
        viewedAt: string;
        id?: string | null;
      }[]
    | null;
  orders?: {
    docs?: (string | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Last successful login time
   */
  lastLoginAt?: string | null;
  location?: {
    /**
     * Geographic coordinates [longitude, latitude]
     *
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
    /**
     * Location accuracy in meters (from browser GPS)
     */
    accuracy?: number | null;
    /**
     * Country name (e.g., Afghanistan)
     */
    country?: string | null;
    /**
     * ISO 3166-1 alpha-2 country code (e.g., AF)
     */
    countryCode?: string | null;
    /**
     * Region/Province/State (e.g., Kabul)
     */
    region?: string | null;
    /**
     * City name
     */
    city?: string | null;
    /**
     * IANA timezone (e.g., Asia/Kabul)
     */
    timezone?: string | null;
    /**
     * How location was obtained
     */
    source?: ('browser' | 'ip' | 'manual') | null;
    /**
     * What event triggered this location capture
     */
    event?: ('login' | 'register' | 'order' | 'browser_permission' | 'verify_email' | 'oauth') | null;
    /**
     * IP address used for geolocation
     */
    ip?: string | null;
    /**
     * Whether user granted browser location permission
     */
    permissionGranted?: boolean | null;
    /**
     * When location was last captured
     */
    lastUpdated?: string | null;
  };
  /**
   * Historical location data (last 10 entries)
   */
  locationHistory?:
    | {
        /**
         * @minItems 2
         * @maxItems 2
         */
        coordinates?: [number, number] | null;
        city?: string | null;
        country?: string | null;
        source?: ('browser' | 'ip') | null;
        event?: ('login' | 'register' | 'order' | 'browser_permission' | 'verify_email' | 'oauth') | null;
        timestamp?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Leave blank to auto-generate from filename
   */
  alt?: string | null;
  uploadedBy?: (string | null) | User;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  /**
   * Average rating (calculated from approved reviews)
   */
  averageRating?: number | null;
  /**
   * Number of approved reviews
   */
  reviewCount?: number | null;
  /**
   * Total number of units sold
   */
  totalSold?: number | null;
  /**
   * Product performance analytics (system-managed)
   */
  analytics?: {
    /**
     * Total number of product page views
     */
    viewCount?: number | null;
    /**
     * Number of unique users who viewed this product
     */
    uniqueViewCount?: number | null;
    /**
     * Number of times product was added to cart
     */
    addToCartCount?: number | null;
    /**
     * Number of times added to wishlist
     */
    wishlistCount?: number | null;
    /**
     * Conversion rate (purchases / views) as percentage
     */
    conversionRate?: number | null;
    /**
     * Cart to purchase rate (purchases / add-to-cart) as percentage
     */
    cartConversionRate?: number | null;
    /**
     * Timestamp of last product view
     */
    lastViewedAt?: string | null;
    /**
     * Track unique users who viewed (for unique view count)
     */
    viewedByUsers?:
      | {
          userId: string;
          viewedAt: string;
          id?: string | null;
        }[]
      | null;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief summary for listings
   */
  shortDescription?: string | null;
  /**
   * Enable if product has variants (size, color, etc.)
   */
  hasVariants?: boolean | null;
  /**
   * ✨ Define options here (e.g., Size: S/M/L, Color: Red/Blue). Variants will be AUTO-GENERATED when you save!
   */
  variantOptions?:
    | {
        /**
         * Option name (e.g., "Size", "Color")
         */
        name: string;
        /**
         * Available values for this option
         */
        values: {
          /**
           * Option value (e.g., "Small", "Red")
           */
          value: string;
          /**
           * Optional: Image for this option (e.g., color swatch, product thumbnail)
           */
          image?: (string | null) | Media;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  price: number;
  salePrice?: number | null;
  currency: 'AFN' | 'USD';
  sku?: string | null;
  /**
   * Enable inventory tracking for this product
   */
  trackQuantity?: boolean | null;
  /**
   * Current stock quantity
   */
  quantity?: number | null;
  /**
   * Alert threshold for low stock
   */
  lowStockThreshold?: number | null;
  /**
   * Product images. Optional if product has variants with their own images.
   */
  images?: (string | Media)[] | null;
  categories?: (string | Category)[] | null;
  publishedAt?: string | null;
  /**
   * Stock status - Auto-managed when inventory tracking is enabled. Manual control when disabled.
   */
  stockStatus: 'in_stock' | 'out_of_stock' | 'low_stock' | 'on_backorder' | 'discontinued';
  featured?: boolean | null;
  /**
   * Allow purchases when out of stock
   */
  allowBackorders?: boolean | null;
  requiresShipping?: boolean | null;
  slug?: string | null;
  slugLock?: boolean | null;
  /**
   * Seller who owns this product (leave empty for platform products). Auto-assigned for sellers.
   */
  seller?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug?: string | null;
  slugLock?: boolean | null;
  smallCategoryImage?: (string | null) | Media;
  description?: string | null;
  heroImage?: (string | null) | Media;
  /**
   * Parent category for hierarchy
   */
  parent?: (string | null) | Category;
  displayOrder?: number | null;
  status: 'active' | 'inactive' | 'hidden';
  featured?: boolean | null;
  showInMenu?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Auto-generated unique order identifier
   */
  orderNumber: string;
  /**
   * Leave empty for guest orders
   */
  customer?: (string | null) | User;
  /**
   * Email for guest checkout orders
   */
  guestEmail?: string | null;
  items: {
    product: string | Product;
    /**
     * Product variant (if applicable)
     */
    variant?: (string | null) | ProductVariant;
    quantity: number;
    price: number;
    total: number;
    /**
     * Snapshot of variant details at time of order (for historical record)
     */
    variantDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Seller who owns this product (auto-populated)
     */
    productSeller?: (string | null) | User;
    id?: string | null;
  }[];
  subtotal: number;
  shipping?: number | null;
  total: number;
  shippingAddress: {
    firstName: string;
    lastName: string;
    state?: string | null;
    country: string;
    phone?: string | null;
    nearbyLandmark?: string | null;
    detailedDirections?: string | null;
    coordinates?: {
      latitude?: number | null;
      longitude?: number | null;
      /**
       * Location accuracy in meters
       */
      accuracy?: number | null;
      /**
       * How the location was obtained
       */
      source?: ('gps' | 'ip' | 'manual' | 'map') | null;
      /**
       * IP address when location was captured
       */
      ip?: string | null;
    };
  };
  trackingNumber?: string | null;
  /**
   * Customer note for this order (e.g., delivery instructions)
   */
  customerNote?: string | null;
  /**
   * Internal notes - only visible to admins and developers
   */
  notes?: string | null;
  status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  paymentMethod?: ('cod' | 'bank_transfer' | 'credit_card') | null;
  currency: 'AFN' | 'USD';
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage product variants (sizes, colors, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
  id: string;
  title?: string | null;
  /**
   * Parent product this variant belongs to
   */
  product: string | Product;
  /**
   * Unique SKU for this variant (e.g., "TSHIRT-M-RED")
   */
  sku: string;
  /**
   * Variant options (e.g., Size: M, Color: Red)
   */
  options: {
    /**
     * Option name (e.g., "Size", "Color")
     */
    name: string;
    /**
     * Option value (e.g., "Medium", "Red")
     */
    value: string;
    id?: string | null;
  }[];
  /**
   * Mark as default variant to display when product is first loaded
   */
  isDefault?: boolean | null;
  /**
   * Override product price (leave empty to use product price)
   */
  price?: number | null;
  /**
   * Original price for sale pricing
   */
  compareAtPrice?: number | null;
  /**
   * Enable inventory tracking for this variant
   */
  trackQuantity?: boolean | null;
  /**
   * Current stock quantity
   */
  quantity?: number | null;
  /**
   * Alert threshold for low stock
   */
  lowStockThreshold?: number | null;
  /**
   * Stock status - Auto-managed when inventory tracking is enabled. Manual control when disabled.
   */
  stockStatus: 'in_stock' | 'out_of_stock' | 'low_stock' | 'on_backorder' | 'discontinued';
  /**
   * Allow purchases when out of stock
   */
  allowBackorders?: boolean | null;
  /**
   * 🎨 Upload variant-specific images here (e.g., different colors). Images auto-switch when customers select this variant!
   */
  images?: (string | Media)[] | null;
  /**
   * Total number of units sold
   */
  totalSold?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  product: string | Product;
  /**
   * Auto-populated with current user
   */
  user: string | User;
  /**
   * Rating from 1 to 5 stars
   */
  rating: number;
  title: string;
  comment: string;
  /**
   * Review moderation status (admins only)
   */
  status: 'pending' | 'approved' | 'rejected';
  /**
   * User purchased this product (auto-verified)
   */
  verifiedPurchase?: boolean | null;
  /**
   * Number of users who found this helpful (auto-calculated)
   */
  helpful?: number | null;
  /**
   * Users who voted this review as helpful (managed via API)
   */
  helpfulVotes?:
    | {
        user?: (string | null) | User;
        votedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Users who voted this review as not helpful (managed via API)
   */
  notHelpfulVotes?:
    | {
        user?: (string | null) | User;
        votedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  images?: (string | null) | Media;
  /**
   * Official response from store admins
   */
  adminResponse?: {
    response?: string | null;
    /**
     * Auto-populated when response is added
     */
    respondedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'product-variants';
        value: string | ProductVariant;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  password?: T;
  firstName?: T;
  lastName?: T;
  authMethods?: T;
  googleSub?: T;
  picture?: T;
  profilePicture?: T;
  ogfan?: T;
  phone?: T;
  roles?: T;
  addresses?:
    | T
    | {
        label?: T;
        firstName?: T;
        lastName?: T;
        state?: T;
        country?: T;
        phone?: T;
        isDefault?: T;
        nearbyLandmark?: T;
        detailedDirections?: T;
        coordinates?:
          | T
          | {
              latitude?: T;
              longitude?: T;
              accuracy?: T;
              source?: T;
              ip?: T;
            };
        id?: T;
      };
  preferences?:
    | T
    | {
        currency?: T;
        newsletter?: T;
      };
  cart?: T;
  wishlist?: T;
  recentlyViewed?:
    | T
    | {
        product?: T;
        viewedAt?: T;
        id?: T;
      };
  orders?: T;
  lastLoginAt?: T;
  location?:
    | T
    | {
        coordinates?: T;
        accuracy?: T;
        country?: T;
        countryCode?: T;
        region?: T;
        city?: T;
        timezone?: T;
        source?: T;
        event?: T;
        ip?: T;
        permissionGranted?: T;
        lastUpdated?: T;
      };
  locationHistory?:
    | T
    | {
        coordinates?: T;
        city?: T;
        country?: T;
        source?: T;
        event?: T;
        timestamp?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slugLock?: T;
  smallCategoryImage?: T;
  description?: T;
  heroImage?: T;
  parent?: T;
  displayOrder?: T;
  status?: T;
  featured?: T;
  showInMenu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  averageRating?: T;
  reviewCount?: T;
  totalSold?: T;
  analytics?:
    | T
    | {
        viewCount?: T;
        uniqueViewCount?: T;
        addToCartCount?: T;
        wishlistCount?: T;
        conversionRate?: T;
        cartConversionRate?: T;
        lastViewedAt?: T;
        viewedByUsers?:
          | T
          | {
              userId?: T;
              viewedAt?: T;
              id?: T;
            };
      };
  description?: T;
  shortDescription?: T;
  hasVariants?: T;
  variantOptions?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              image?: T;
              id?: T;
            };
        id?: T;
      };
  price?: T;
  salePrice?: T;
  currency?: T;
  sku?: T;
  trackQuantity?: T;
  quantity?: T;
  lowStockThreshold?: T;
  images?: T;
  categories?: T;
  publishedAt?: T;
  stockStatus?: T;
  featured?: T;
  allowBackorders?: T;
  requiresShipping?: T;
  slug?: T;
  slugLock?: T;
  seller?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  sku?: T;
  options?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  isDefault?: T;
  price?: T;
  compareAtPrice?: T;
  trackQuantity?: T;
  quantity?: T;
  lowStockThreshold?: T;
  stockStatus?: T;
  allowBackorders?: T;
  images?: T;
  totalSold?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  guestEmail?: T;
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        price?: T;
        total?: T;
        variantDetails?: T;
        productSeller?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  total?: T;
  shippingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        state?: T;
        country?: T;
        phone?: T;
        nearbyLandmark?: T;
        detailedDirections?: T;
        coordinates?:
          | T
          | {
              latitude?: T;
              longitude?: T;
              accuracy?: T;
              source?: T;
              ip?: T;
            };
      };
  trackingNumber?: T;
  customerNote?: T;
  notes?: T;
  status?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  user?: T;
  rating?: T;
  title?: T;
  comment?: T;
  status?: T;
  verifiedPurchase?: T;
  helpful?: T;
  helpfulVotes?:
    | T
    | {
        user?: T;
        votedAt?: T;
        id?: T;
      };
  notHelpfulVotes?:
    | T
    | {
        user?: T;
        votedAt?: T;
        id?: T;
      };
  images?: T;
  adminResponse?:
    | T
    | {
        response?: T;
        respondedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms".
 */
export interface Term {
  id: string;
  /**
   * The title that appears at the top of the page
   */
  title: string;
  /**
   * The full terms and conditions content
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Date when terms were last updated
   */
  lastUpdated?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: string;
  /**
   * The title that appears at the top of the page
   */
  title: string;
  /**
   * The full privacy policy content
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Date when privacy policy was last updated
   */
  lastUpdated?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help".
 */
export interface Help {
  id: string;
  /**
   * عنوان که در بالای صفحه نمایش داده می‌شود
   */
  title: string;
  /**
   * محتوای کامل مرکز راهنمایی
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * تاریخ آخرین بروزرسانی
   */
  lastUpdated?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping".
 */
export interface Shipping {
  id: string;
  /**
   * عنوان که در بالای صفحه نمایش داده می‌شود
   */
  title: string;
  /**
   * اطلاعات کامل ارسال و بازگشت کالا
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * تاریخ آخرین بروزرسانی
   */
  lastUpdated?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: string;
  title: string;
  /**
   * ایمیل
   */
  email: string;
  /**
   * شماره تماس
   */
  phone: string;
  /**
   * شماره واتساپ (اختیاری)
   */
  whatsapp?: string | null;
  address: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lastUpdated?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  /**
   * عنوان که در بالای صفحه نمایش داده می‌شود
   */
  title: string;
  /**
   * لیست سوالات متداول
   */
  items: {
    /**
     * سوال
     */
    question: string;
    /**
     * پاسخ به سوال
     */
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  /**
   * تاریخ آخرین بروزرسانی
   */
  lastUpdated?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  shippingMode?: ('always_free' | 'free_above_threshold' | 'always_charged') | null;
  /**
   * The shipping fee charged to customers
   */
  shippingCost?: number | null;
  /**
   * Orders above this amount qualify for free delivery
   */
  freeDeliveryThreshold?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms_select".
 */
export interface TermsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  title?: T;
  content?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help_select".
 */
export interface HelpSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping_select".
 */
export interface ShippingSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  title?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  address?: T;
  content?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  shippingMode?: T;
  shippingCost?: T;
  freeDeliveryThreshold?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'products';
      value: string | Product;
    } | null;
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}